name: spectral-resnet18-cifar100
dataset: 
  name: cifar100
  image_size: 32
  num_workers: 4
  numclasses: 100

model: 
  name: spectral
  backbone: resnet18_cifar_variant1_mlp_norelu
  mu: 1
  numclasses: 100

train:
  optimizer: 
    name: sgd
    weight_decay: 0.0005
    momentum: 0.9
  warmup_epochs: 10
  warmup_lr: 0
  base_lr: 0.03
  final_lr: 0
  num_epochs: 1200 # this parameter influence the lr decay
  stop_at_epoch: 1200 # has to be smaller than num_epochs
  batch_size: 512
  knn_monitor: True # knn monitor will take more time
  knn_interval: 1
  knn_k: 200
eval: # linear evaluation, False will turn off automatic evaluation after training
  optimizer: 
    name: sgd
    weight_decay: 0
    momentum: 0.9
  warmup_lr: 0
  warmup_epochs: 0
  base_lr: 30
  final_lr: 0
  batch_size: 128
  num_epochs: 100

logger:
  tensorboard: True
  matplotlib: True

# two things might lead to stochastic behavior other than seed:
# worker_init_fn from dataloader and torch.nn.functional.interpolate 
# (keep this in mind if you want to achieve 100% deterministic)




